swagger: "2.0"
info:
  title: cg-auth-api
  description: cidesa group api for user authorization
  version: 1.0.0
basePath: /api/v1
paths:
  /users:
    get:
      description: get list of users
      operationId: getUsers
      tags:
        - Users
      parameters:
        - name: limit
          type: integer
          in: query
          default: 20
        - name: offset
          type: integer
          in: query
        - name: username
          type: string
          in: query
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/users-response"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/default"
            
    post:
      description: create a new user
      operationId: createUser
      tags:
        - Users
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              passwordHash:
                type: string
              email: 
                type: string
              firstname:
                type: string
              lastname:
                type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/user-response"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/default"
                
  /users/{username}:
    get:
      description: get a single user by username
      operationId: getUserByUsername
      tags:
        - Users
      parameters:
        - name: username
          in: path
          type: string
          required: true
      responses:
        200:
          description: successful operation
          schema: 
            $ref: "#/definitions/user-response"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/default"
    patch:
      description: update a single user
      operationId: updateUser 
      tags:
        - Users
      parameters:
        - name: username
          type: string
          in: path
          required: true

        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              passwordHash:
                type: string
              email: 
                type: string
              firstname:
                type: string
              lastname:
                type: string
                
      responses:
        200:
          description: successful operation 
          schema:
            $ref: "#/definitions/user-response"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/default"
    
    delete:
      description: delete a single user
      operationId: deleteUser
      tags:
        - Users
      parameters:
        - name: username
          in: path
          type: string
          required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
            properties:
              status:
                type: string
                default: success
              data:
                type: string
                description: operation message
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/default"
          
tags:
  - name: Users
    description: users endpoints

definitions:
  default:
    type: object
    properties:
      status:
        type: string
        description: success or error
      data:
        type: string
        description: message of what went wrong
  user:
    type: object
    properties:
      id:
        type: integer
      username:
        type: string
      email: 
        type: string
      firstname:
        type: string
      lastname:
        type: string
    
  user-response:
    type: object
    properties:
      status:
        type: string
      data:
        $ref: "#/definitions/user"
        
  users-response:
    type: object
    properties:
      status:
        type: string
      data:
        type: array
        items:
          $ref: "#/definitions/user"
